const group = [
  "Benjamin Gouget",
  "Florian Farris",
  "Said Zenafi",
  "Yannis Aouachria",
  "Pierre Denaes",
  "Morgan Trainoir",
  "Coralie Damery",
  "Quentin Robert",
  "Alexandre Chauvet",
  "Sebastien Cartoux",
  "Davis Haas",
  "Sofiane Sotehi",
  "Yoan Baldacchino",
  "Nicolas Degabriel",
  "Ayman Bratzu",
  "Quentin Queffurus",
  "Killian Pasquier",
  "Jérôme Laurent",
  "Jean-Daniel Pontremoli",
  "Marjorie Ngoupende",
  "Christophe Coutures",
  "Christophe Michel"
];

const groupNames = [
  "Fearless Widowmakers",
  "Collapsed Wolverines",
  "Mystical Legion",
  "Birth of Honor",
  "Torment of the Owl",
  "Howl of the Cosmos",
  "Angels of the Forbidden",
  "Lightningcrushers",
  "Magicclouds",
  "Shadowmight",
  "Hidden War",
  "Phobic Intent",
  "Discarded Honour",
  "Avenging of the Noble",
  "Mages from the Mountains",
  "Boon of the Dead",
  "Secret of the Devoted",
  "Rumblegarde",
  "Howling Dragons",
  "Stormblades",
  "Dispensable Champions",
  "Forsaken Hooligans",
  "Trusted Champions",
  "Ghosts of the Bull",
  "Boon of the Tiger",
  "Storm of the Natural",
  "Spirits of the Departed",
  "Monsterfall",
  "Poisonscars",
  "Gentlegarde"
];
