const group = [
  "user 1",
  "user 2",
  "user 3",
  "user 4",
  "user 5",
  "user 6",
  "user 7",
  "user 8",
  "user 9",
  "user 10",
  "user 11",
  "user 12",
  "user 13",
  "user 14",
  "user 15",
  "user 16",
  "user 17",
  "user 18",
  "user 19",
  "user 20",
  "user 21",
  "user 22",
];

// generated names courtesy of https://www.fantasynamegenerators.com/
const groupNames = [
  "Fearless Widowmakers",
  "Collapsed Wolverines",
  "Mystical Legion",
  "Birth of Honor",
  "Torment of the Owl",
  "Howl of the Cosmos",
  "Angels of the Forbidden",
  "Lightningcrushers",
  "Magicclouds",
  "Shadowmight",
  "Hidden War",
  "Phobic Intent",
  "Discarded Honour",
  "Avenging of the Noble",
  "Mages from the Mountains",
  "Boon of the Dead",
  "Secret of the Devoted",
  "Rumblegarde",
  "Howling Dragons",
  "Stormblades",
  "Dispensable Champions",
  "Forsaken Hooligans",
  "Trusted Champions",
  "Ghosts of the Bull",
  "Boon of the Tiger",
  "Storm of the Natural",
  "Spirits of the Departed",
  "Monsterfall",
  "Poisonscars",
  "Gentlegarde",
];
